
@startmindmap

title LINKS

skinparam shadowing false
skinparam backgroundColor #EEEBDC
skinparam ArrowColor black
skinparam noteBorderColor black

+ 0
++_ [[ .git ]]
+++_ [[ .github ]]
++_ [[ .vscode ]]
++_ [[ 0to100-latest ]]
++_ [[ _tmp ]]
++_ [[ https///cloud.google.com/docs ]]
++_ [[ https///storage.googleapis.com/cloud-training/cls-html5-courses/T-BQRS-I/M1/index.html ]]
++_ [[ https///storage.googleapis.com/cloud-training/cls-html5-courses/T-BQRS-I/M2/index.html ]]
++_ [[ https///storage.googleapis.com/cloud-training/cls-html5-courses/T-BQRS-I/M3/index.html ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/documents/343621 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/labs/343580 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/labs/343602 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343555 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343556 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343561 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343571 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343583 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343605 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3062553/video/343612 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/documents/379272 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/labs/379232 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/labs/379242 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/labs/379246 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/labs/379250 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/labs/379262 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/labs/379269 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/video/379215 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/video/379216 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/video/379223 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/video/379235 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/video/379255 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3591643/video/379271 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3605921/video/337128 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3605921/video/337129 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/documents/376394 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/labs/376367 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/labs/376377 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/labs/376387 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/labs/376391 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376357 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376358 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376363 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376369 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376370 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376379 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376383 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3631336/video/376393 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/documents/375643 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/labs/375617 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/labs/375621 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/labs/375624 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/labs/375631 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/labs/375633 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/labs/375640 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/video/375610 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/video/375612 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/video/375619 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/video/375625 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/video/375635 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3671937/video/375642 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/documents/382288 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/labs/382256 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/labs/382266 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/labs/382275 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/labs/382283 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/video/382241 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/video/382243 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/video/382258 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/video/382268 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3724532/video/382287 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/labs/383335 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/labs/383347 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/labs/383359 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/labs/383379 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383324 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383327 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383339 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383351 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383363 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383373 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3751705/video/383384 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3777998/documents/375036 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3777998/documents/375039 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3777998/documents/375041 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3777998/labs/375038 ]]
++_ [[ https///www.cloudskillsboost.google/course_sessions/3777998/labs/375043 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/14 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/24 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/3 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/443 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/484 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/512 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/52 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/53 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/54 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/72 ]]
++_ [[ https///www.cloudskillsboost.google/course_templates/86 ]]
++_ [[ https///www.cloudskillsboost.google/focuses/10258//parent/=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/10258/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/10285/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/1035/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/10457/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/11999/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/12007//parent/=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/15657/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/1763/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/1843/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/18478/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/18940/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/2794//parent/=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3460/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3483/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3528/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3563//parent/=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3632/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3638/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3640/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3694/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/3696/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/4415/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/557/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/563//parent/=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/569/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/577/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/582/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/584/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/62706/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/63244/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/7140/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/878//parent/=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/916/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/focuses/925/parent=catalog ]]
++_ [[ https///www.cloudskillsboost.google/games/4111 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26478 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26479 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26480 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26482 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26483 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26484 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26485 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26486 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26487 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26488 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4111/labs/26492 ]]
++_ [[ https///www.cloudskillsboost.google/games/4112 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26498 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26499 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26502 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26504 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26505 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26507 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26510 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26511 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26512 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26513 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26515 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4112/labs/26516 ]]
++_ [[ https///www.cloudskillsboost.google/games/4255/labs/27514 ]]
++_ [[ https///www.cloudskillsboost.google/games/4255/labs/27515 ]]
++_ [[ https///www.cloudskillsboost.google/games/4255/labs/27517 ]]
++_ [[ https///www.cloudskillsboost.google/games/4301 ]]
+++_ [[ https///www.cloudskillsboost.google/games/4301/labs/27851 ]]
++_ [[ https///www.cloudskillsboost.google/journeys/16 ]]
++_ [[ https///www.cloudskillsboost.google/public_profiles/0e4d9285-4960-419a-bfb3-1ed19850308c ]]
++_ [[ https///www.cloudskillsboost.google/quests/116 ]]
++_ [[ https///www.cloudskillsboost.google/quests/120 ]]
++_ [[ https///www.cloudskillsboost.google/quests/141 ]]
++_ [[ https///www.cloudskillsboost.google/quests/25 ]]
++_ [[ https///www.cloudskillsboost.google/quests/279 ]]
++_ [[ https///www.cloudskillsboost.google/quests/285 ]]
++_ [[ https///www.cloudskillsboost.google/quests/286 ]]
++_ [[ https///www.cloudskillsboost.google/quests/289 ]]
++_ [[ https///www.cloudskillsboost.google/quests/290 ]]
++_ [[ https///www.cloudskillsboost.google/quests/291 ]]
++_ [[ https///www.cloudskillsboost.google/quests/300 ]]
++_ [[ https///www.cloudskillsboost.google/quests/302 ]]
++_ [[ https///www.cloudskillsboost.google/quests/303 ]]
++_ [[ https///www.cloudskillsboost.google/quests/304 ]]
++_ [[ https///www.cloudskillsboost.google/quests/34 ]]
++_ [[ https///www.cloudskillsboost.google/quests/40 ]]
++_ [[ https///www.cloudskillsboost.google/quests/68 ]]
++_ [[ https///www.cloudskillsboost.google/quests/70 ]]
++_ [[ https///www.cloudskillsboost.google/quests/84 ]]

@endmindmap
        