repos:
  - repo: "https://github.com/psf/black"
    rev: "22.3.0"
    hooks:
      - id: "black"
        name: "Format code (black)"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v3.4.0"
    hooks:
      - id: "check-toml"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"

  - repo: local
    hooks:
      - id: pylint
        name: "Lint code (pylint)"
        entry: pylint
        language: system
        types: [ python ]

  - repo: local
    hooks:
      - id: pytest
        name: "Tests (pytest)"
        entry: pytest zero_to_one_hundred
        language: system
        types: [ python ]
